/*

	EXEC [dbo].[GET_LAST_MODIFIED]
		@P_TABLE_SCHEMA = N'dbo'
	,	@P_TABLE_NAME = 'EMPTY';
--	,	@P_TABLE_NAME = 'publishers';

*/
ALTER PROCEDURE [dbo].[GET_LAST_MODIFIED]
	@P_TABLE_SCHEMA		NVARCHAR(50)
,	@P_TABLE_NAME		NVARCHAR(50)
AS
BEGIN
	DECLARE 
		@LAST_MODIFIED		DATETIME
	,	@SQL				NVARCHAR(4000);

	SET @SQL = CONCAT(
					N'SELECT @LAST_MODIFIED_OUT = MAX([LAST_MODIFIED]) '
				,	N'FROM '
				,	@P_TABLE_SCHEMA
				,	N'.'
				,	@P_TABLE_NAME
				);

/*
	SELECT @SQL;
*/

	EXEC sp_executesql
		@SQL
	,	N'@LAST_MODIFIED_OUT DATETIME OUTPUT'
	,	@LAST_MODIFIED_OUT = @LAST_MODIFIED OUTPUT;

	-- Handle edge case where @LAST_MODIFIED IS NULL;
	-- this will happen if the table is empty.
	SELECT
		IIF(@LAST_MODIFIED IS NOT NULL
	,	@LAST_MODIFIED
	,	CONVERT(DATETIME, '18991231')
	) AS [LAST_MODIFIED];
END
